CREATE TABLE CurrencyRequest (
    id INT      PRIMARY KEY AUTO_INCREMENT,
    userId      INT NOT NULL,
    price       VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
